[env]
EDITOR = "hx"
VISUAL = "hx"

[tools]
bat = "latest"
bottom = "latest"
codex = "latest"
elixir = "latest"
erlang = "latest"
"github:elixir-lang/expert" = "nightly"
flyctl = "latest"
fzf = "latest"
github-cli = "latest"
glab = "latest"
go = "latest"
lazygit = "latest"
"github:joelpaulkoch/mdy" = "latest"
node = "latest"
python = "latest"
resvg = "latest"
rust = "latest"
tokei = "latest"
websocat = "latest"
zig = "latest"
zls = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "ruby"]

