theme = "catppuccin_macchiato"

[editor]
auto-save = true
auto-format = true
auto-completion = false
auto-info = true
preview-completion-insert = true
completion-replace = false
line-number = "absolute"
cursorline = true
continue-comments = false
end-of-line-diagnostics = "disable"
bufferline = "multiple"
atomic-save = true

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = false
display-messages = true
display-inlay-hints = false

[editor.statusline]
center = ["version-control"]

[editor.inline-diagnostics]
cursor-line = "disable"
other-lines = "disable"

[keys.normal]
# Print the current line's git blame information to the statusline.
space.B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
space.space = [":insert-output echo %{buffer_name}:%{cursor_line}", "yank_main_selection_to_primary_clipboard", "normal_mode", "delete_selection"]
